// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/accesstokens"
	"authorization-service/ent/clients"
	"authorization-service/ent/session"
	"context"
	"errors"
	"fmt"
	"net/url"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"golang.org/x/text/language"
)

// AccessTokensCreate is the builder for creating a AccessTokens entity.
type AccessTokensCreate struct {
	config
	mutation *AccessTokensMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (atc *AccessTokensCreate) SetRequestID(s string) *AccessTokensCreate {
	atc.mutation.SetRequestID(s)
	return atc
}

// SetRequestedAt sets the "requestedAt" field.
func (atc *AccessTokensCreate) SetRequestedAt(t time.Time) *AccessTokensCreate {
	atc.mutation.SetRequestedAt(t)
	return atc
}

// SetScopes sets the "scopes" field.
func (atc *AccessTokensCreate) SetScopes(s []string) *AccessTokensCreate {
	atc.mutation.SetScopes(s)
	return atc
}

// SetGrantedScopes sets the "granted_scopes" field.
func (atc *AccessTokensCreate) SetGrantedScopes(s []string) *AccessTokensCreate {
	atc.mutation.SetGrantedScopes(s)
	return atc
}

// SetRequestedAudience sets the "requested_audience" field.
func (atc *AccessTokensCreate) SetRequestedAudience(s []string) *AccessTokensCreate {
	atc.mutation.SetRequestedAudience(s)
	return atc
}

// SetGrantedAudience sets the "granted_audience" field.
func (atc *AccessTokensCreate) SetGrantedAudience(s []string) *AccessTokensCreate {
	atc.mutation.SetGrantedAudience(s)
	return atc
}

// SetForm sets the "form" field.
func (atc *AccessTokensCreate) SetForm(u url.Values) *AccessTokensCreate {
	atc.mutation.SetForm(u)
	return atc
}

// SetLang sets the "lang" field.
func (atc *AccessTokensCreate) SetLang(l language.Tag) *AccessTokensCreate {
	atc.mutation.SetLang(l)
	return atc
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (atc *AccessTokensCreate) SetNillableLang(l *language.Tag) *AccessTokensCreate {
	if l != nil {
		atc.SetLang(*l)
	}
	return atc
}

// SetID sets the "id" field.
func (atc *AccessTokensCreate) SetID(s string) *AccessTokensCreate {
	atc.mutation.SetID(s)
	return atc
}

// SetClientIDID sets the "client_id" edge to the Clients entity by ID.
func (atc *AccessTokensCreate) SetClientIDID(id string) *AccessTokensCreate {
	atc.mutation.SetClientIDID(id)
	return atc
}

// SetNillableClientIDID sets the "client_id" edge to the Clients entity by ID if the given value is not nil.
func (atc *AccessTokensCreate) SetNillableClientIDID(id *string) *AccessTokensCreate {
	if id != nil {
		atc = atc.SetClientIDID(*id)
	}
	return atc
}

// SetClientID sets the "client_id" edge to the Clients entity.
func (atc *AccessTokensCreate) SetClientID(c *Clients) *AccessTokensCreate {
	return atc.SetClientIDID(c.ID)
}

// SetSessionIDID sets the "session_id" edge to the Session entity by ID.
func (atc *AccessTokensCreate) SetSessionIDID(id string) *AccessTokensCreate {
	atc.mutation.SetSessionIDID(id)
	return atc
}

// SetNillableSessionIDID sets the "session_id" edge to the Session entity by ID if the given value is not nil.
func (atc *AccessTokensCreate) SetNillableSessionIDID(id *string) *AccessTokensCreate {
	if id != nil {
		atc = atc.SetSessionIDID(*id)
	}
	return atc
}

// SetSessionID sets the "session_id" edge to the Session entity.
func (atc *AccessTokensCreate) SetSessionID(s *Session) *AccessTokensCreate {
	return atc.SetSessionIDID(s.ID)
}

// Mutation returns the AccessTokensMutation object of the builder.
func (atc *AccessTokensCreate) Mutation() *AccessTokensMutation {
	return atc.mutation
}

// Save creates the AccessTokens in the database.
func (atc *AccessTokensCreate) Save(ctx context.Context) (*AccessTokens, error) {
	return withHooks(ctx, atc.sqlSave, atc.mutation, atc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AccessTokensCreate) SaveX(ctx context.Context) *AccessTokens {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atc *AccessTokensCreate) Exec(ctx context.Context) error {
	_, err := atc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atc *AccessTokensCreate) ExecX(ctx context.Context) {
	if err := atc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atc *AccessTokensCreate) check() error {
	if _, ok := atc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "AccessTokens.request_id"`)}
	}
	if _, ok := atc.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requestedAt", err: errors.New(`ent: missing required field "AccessTokens.requestedAt"`)}
	}
	if _, ok := atc.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "AccessTokens.scopes"`)}
	}
	if _, ok := atc.mutation.GrantedScopes(); !ok {
		return &ValidationError{Name: "granted_scopes", err: errors.New(`ent: missing required field "AccessTokens.granted_scopes"`)}
	}
	if _, ok := atc.mutation.RequestedAudience(); !ok {
		return &ValidationError{Name: "requested_audience", err: errors.New(`ent: missing required field "AccessTokens.requested_audience"`)}
	}
	if _, ok := atc.mutation.GrantedAudience(); !ok {
		return &ValidationError{Name: "granted_audience", err: errors.New(`ent: missing required field "AccessTokens.granted_audience"`)}
	}
	if _, ok := atc.mutation.Form(); !ok {
		return &ValidationError{Name: "form", err: errors.New(`ent: missing required field "AccessTokens.form"`)}
	}
	return nil
}

func (atc *AccessTokensCreate) sqlSave(ctx context.Context) (*AccessTokens, error) {
	if err := atc.check(); err != nil {
		return nil, err
	}
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AccessTokens.ID type: %T", _spec.ID.Value)
		}
	}
	atc.mutation.id = &_node.ID
	atc.mutation.done = true
	return _node, nil
}

func (atc *AccessTokensCreate) createSpec() (*AccessTokens, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessTokens{config: atc.config}
		_spec = sqlgraph.NewCreateSpec(accesstokens.Table, sqlgraph.NewFieldSpec(accesstokens.FieldID, field.TypeString))
	)
	if id, ok := atc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := atc.mutation.RequestID(); ok {
		_spec.SetField(accesstokens.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := atc.mutation.RequestedAt(); ok {
		_spec.SetField(accesstokens.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := atc.mutation.Scopes(); ok {
		_spec.SetField(accesstokens.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := atc.mutation.GrantedScopes(); ok {
		_spec.SetField(accesstokens.FieldGrantedScopes, field.TypeJSON, value)
		_node.GrantedScopes = value
	}
	if value, ok := atc.mutation.RequestedAudience(); ok {
		_spec.SetField(accesstokens.FieldRequestedAudience, field.TypeJSON, value)
		_node.RequestedAudience = value
	}
	if value, ok := atc.mutation.GrantedAudience(); ok {
		_spec.SetField(accesstokens.FieldGrantedAudience, field.TypeJSON, value)
		_node.GrantedAudience = value
	}
	if value, ok := atc.mutation.Form(); ok {
		_spec.SetField(accesstokens.FieldForm, field.TypeJSON, value)
		_node.Form = value
	}
	if value, ok := atc.mutation.Lang(); ok {
		_spec.SetField(accesstokens.FieldLang, field.TypeJSON, value)
		_node.Lang = value
	}
	if nodes := atc.mutation.ClientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstokens.ClientIDTable,
			Columns: []string{accesstokens.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.clients_access_token = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := atc.mutation.SessionIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accesstokens.SessionIDTable,
			Columns: []string{accesstokens.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_access_token = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccessTokensCreateBulk is the builder for creating many AccessTokens entities in bulk.
type AccessTokensCreateBulk struct {
	config
	builders []*AccessTokensCreate
}

// Save creates the AccessTokens entities in the database.
func (atcb *AccessTokensCreateBulk) Save(ctx context.Context) ([]*AccessTokens, error) {
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AccessTokens, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessTokensMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atcb *AccessTokensCreateBulk) SaveX(ctx context.Context) []*AccessTokens {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atcb *AccessTokensCreateBulk) Exec(ctx context.Context) error {
	_, err := atcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atcb *AccessTokensCreateBulk) ExecX(ctx context.Context) {
	if err := atcb.Exec(ctx); err != nil {
		panic(err)
	}
}
