// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/authorizecodes"
	"authorization-service/ent/predicate"
	"authorization-service/ent/request"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizeCodesQuery is the builder for querying AuthorizeCodes entities.
type AuthorizeCodesQuery struct {
	config
	ctx           *QueryContext
	order         []authorizecodes.OrderOption
	inters        []Interceptor
	predicates    []predicate.AuthorizeCodes
	withRequestID *RequestQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuthorizeCodesQuery builder.
func (acq *AuthorizeCodesQuery) Where(ps ...predicate.AuthorizeCodes) *AuthorizeCodesQuery {
	acq.predicates = append(acq.predicates, ps...)
	return acq
}

// Limit the number of records to be returned by this query.
func (acq *AuthorizeCodesQuery) Limit(limit int) *AuthorizeCodesQuery {
	acq.ctx.Limit = &limit
	return acq
}

// Offset to start from.
func (acq *AuthorizeCodesQuery) Offset(offset int) *AuthorizeCodesQuery {
	acq.ctx.Offset = &offset
	return acq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (acq *AuthorizeCodesQuery) Unique(unique bool) *AuthorizeCodesQuery {
	acq.ctx.Unique = &unique
	return acq
}

// Order specifies how the records should be ordered.
func (acq *AuthorizeCodesQuery) Order(o ...authorizecodes.OrderOption) *AuthorizeCodesQuery {
	acq.order = append(acq.order, o...)
	return acq
}

// QueryRequestID chains the current query on the "request_id" edge.
func (acq *AuthorizeCodesQuery) QueryRequestID() *RequestQuery {
	query := (&RequestClient{config: acq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := acq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := acq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(authorizecodes.Table, authorizecodes.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, authorizecodes.RequestIDTable, authorizecodes.RequestIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(acq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AuthorizeCodes entity from the query.
// Returns a *NotFoundError when no AuthorizeCodes was found.
func (acq *AuthorizeCodesQuery) First(ctx context.Context) (*AuthorizeCodes, error) {
	nodes, err := acq.Limit(1).All(setContextOp(ctx, acq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{authorizecodes.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) FirstX(ctx context.Context) *AuthorizeCodes {
	node, err := acq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuthorizeCodes ID from the query.
// Returns a *NotFoundError when no AuthorizeCodes ID was found.
func (acq *AuthorizeCodesQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = acq.Limit(1).IDs(setContextOp(ctx, acq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{authorizecodes.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) FirstIDX(ctx context.Context) string {
	id, err := acq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuthorizeCodes entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuthorizeCodes entity is found.
// Returns a *NotFoundError when no AuthorizeCodes entities are found.
func (acq *AuthorizeCodesQuery) Only(ctx context.Context) (*AuthorizeCodes, error) {
	nodes, err := acq.Limit(2).All(setContextOp(ctx, acq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{authorizecodes.Label}
	default:
		return nil, &NotSingularError{authorizecodes.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) OnlyX(ctx context.Context) *AuthorizeCodes {
	node, err := acq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuthorizeCodes ID in the query.
// Returns a *NotSingularError when more than one AuthorizeCodes ID is found.
// Returns a *NotFoundError when no entities are found.
func (acq *AuthorizeCodesQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = acq.Limit(2).IDs(setContextOp(ctx, acq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{authorizecodes.Label}
	default:
		err = &NotSingularError{authorizecodes.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) OnlyIDX(ctx context.Context) string {
	id, err := acq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuthorizeCodesSlice.
func (acq *AuthorizeCodesQuery) All(ctx context.Context) ([]*AuthorizeCodes, error) {
	ctx = setContextOp(ctx, acq.ctx, "All")
	if err := acq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuthorizeCodes, *AuthorizeCodesQuery]()
	return withInterceptors[[]*AuthorizeCodes](ctx, acq, qr, acq.inters)
}

// AllX is like All, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) AllX(ctx context.Context) []*AuthorizeCodes {
	nodes, err := acq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuthorizeCodes IDs.
func (acq *AuthorizeCodesQuery) IDs(ctx context.Context) (ids []string, err error) {
	if acq.ctx.Unique == nil && acq.path != nil {
		acq.Unique(true)
	}
	ctx = setContextOp(ctx, acq.ctx, "IDs")
	if err = acq.Select(authorizecodes.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) IDsX(ctx context.Context) []string {
	ids, err := acq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (acq *AuthorizeCodesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, acq.ctx, "Count")
	if err := acq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, acq, querierCount[*AuthorizeCodesQuery](), acq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) CountX(ctx context.Context) int {
	count, err := acq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (acq *AuthorizeCodesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, acq.ctx, "Exist")
	switch _, err := acq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (acq *AuthorizeCodesQuery) ExistX(ctx context.Context) bool {
	exist, err := acq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuthorizeCodesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (acq *AuthorizeCodesQuery) Clone() *AuthorizeCodesQuery {
	if acq == nil {
		return nil
	}
	return &AuthorizeCodesQuery{
		config:        acq.config,
		ctx:           acq.ctx.Clone(),
		order:         append([]authorizecodes.OrderOption{}, acq.order...),
		inters:        append([]Interceptor{}, acq.inters...),
		predicates:    append([]predicate.AuthorizeCodes{}, acq.predicates...),
		withRequestID: acq.withRequestID.Clone(),
		// clone intermediate query.
		sql:  acq.sql.Clone(),
		path: acq.path,
	}
}

// WithRequestID tells the query-builder to eager-load the nodes that are connected to
// the "request_id" edge. The optional arguments are used to configure the query builder of the edge.
func (acq *AuthorizeCodesQuery) WithRequestID(opts ...func(*RequestQuery)) *AuthorizeCodesQuery {
	query := (&RequestClient{config: acq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	acq.withRequestID = query
	return acq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Active bool `json:"active,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuthorizeCodes.Query().
//		GroupBy(authorizecodes.FieldActive).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (acq *AuthorizeCodesQuery) GroupBy(field string, fields ...string) *AuthorizeCodesGroupBy {
	acq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AuthorizeCodesGroupBy{build: acq}
	grbuild.flds = &acq.ctx.Fields
	grbuild.label = authorizecodes.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Active bool `json:"active,omitempty"`
//	}
//
//	client.AuthorizeCodes.Query().
//		Select(authorizecodes.FieldActive).
//		Scan(ctx, &v)
func (acq *AuthorizeCodesQuery) Select(fields ...string) *AuthorizeCodesSelect {
	acq.ctx.Fields = append(acq.ctx.Fields, fields...)
	sbuild := &AuthorizeCodesSelect{AuthorizeCodesQuery: acq}
	sbuild.label = authorizecodes.Label
	sbuild.flds, sbuild.scan = &acq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuthorizeCodesSelect configured with the given aggregations.
func (acq *AuthorizeCodesQuery) Aggregate(fns ...AggregateFunc) *AuthorizeCodesSelect {
	return acq.Select().Aggregate(fns...)
}

func (acq *AuthorizeCodesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range acq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, acq); err != nil {
				return err
			}
		}
	}
	for _, f := range acq.ctx.Fields {
		if !authorizecodes.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if acq.path != nil {
		prev, err := acq.path(ctx)
		if err != nil {
			return err
		}
		acq.sql = prev
	}
	return nil
}

func (acq *AuthorizeCodesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuthorizeCodes, error) {
	var (
		nodes       = []*AuthorizeCodes{}
		withFKs     = acq.withFKs
		_spec       = acq.querySpec()
		loadedTypes = [1]bool{
			acq.withRequestID != nil,
		}
	)
	if acq.withRequestID != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, authorizecodes.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuthorizeCodes).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuthorizeCodes{config: acq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, acq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := acq.withRequestID; query != nil {
		if err := acq.loadRequestID(ctx, query, nodes, nil,
			func(n *AuthorizeCodes, e *Request) { n.Edges.RequestID = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (acq *AuthorizeCodesQuery) loadRequestID(ctx context.Context, query *RequestQuery, nodes []*AuthorizeCodes, init func(*AuthorizeCodes), assign func(*AuthorizeCodes, *Request)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*AuthorizeCodes)
	for i := range nodes {
		if nodes[i].request_authorize_code == nil {
			continue
		}
		fk := *nodes[i].request_authorize_code
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(request.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "request_authorize_code" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (acq *AuthorizeCodesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := acq.querySpec()
	_spec.Node.Columns = acq.ctx.Fields
	if len(acq.ctx.Fields) > 0 {
		_spec.Unique = acq.ctx.Unique != nil && *acq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, acq.driver, _spec)
}

func (acq *AuthorizeCodesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(authorizecodes.Table, authorizecodes.Columns, sqlgraph.NewFieldSpec(authorizecodes.FieldID, field.TypeString))
	_spec.From = acq.sql
	if unique := acq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if acq.path != nil {
		_spec.Unique = true
	}
	if fields := acq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authorizecodes.FieldID)
		for i := range fields {
			if fields[i] != authorizecodes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := acq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := acq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := acq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := acq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (acq *AuthorizeCodesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(acq.driver.Dialect())
	t1 := builder.Table(authorizecodes.Table)
	columns := acq.ctx.Fields
	if len(columns) == 0 {
		columns = authorizecodes.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if acq.sql != nil {
		selector = acq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if acq.ctx.Unique != nil && *acq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range acq.predicates {
		p(selector)
	}
	for _, p := range acq.order {
		p(selector)
	}
	if offset := acq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := acq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuthorizeCodesGroupBy is the group-by builder for AuthorizeCodes entities.
type AuthorizeCodesGroupBy struct {
	selector
	build *AuthorizeCodesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (acgb *AuthorizeCodesGroupBy) Aggregate(fns ...AggregateFunc) *AuthorizeCodesGroupBy {
	acgb.fns = append(acgb.fns, fns...)
	return acgb
}

// Scan applies the selector query and scans the result into the given value.
func (acgb *AuthorizeCodesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acgb.build.ctx, "GroupBy")
	if err := acgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthorizeCodesQuery, *AuthorizeCodesGroupBy](ctx, acgb.build, acgb, acgb.build.inters, v)
}

func (acgb *AuthorizeCodesGroupBy) sqlScan(ctx context.Context, root *AuthorizeCodesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(acgb.fns))
	for _, fn := range acgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*acgb.flds)+len(acgb.fns))
		for _, f := range *acgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*acgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuthorizeCodesSelect is the builder for selecting fields of AuthorizeCodes entities.
type AuthorizeCodesSelect struct {
	*AuthorizeCodesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (acs *AuthorizeCodesSelect) Aggregate(fns ...AggregateFunc) *AuthorizeCodesSelect {
	acs.fns = append(acs.fns, fns...)
	return acs
}

// Scan applies the selector query and scans the result into the given value.
func (acs *AuthorizeCodesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, acs.ctx, "Select")
	if err := acs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthorizeCodesQuery, *AuthorizeCodesSelect](ctx, acs.AuthorizeCodesQuery, acs, acs.inters, v)
}

func (acs *AuthorizeCodesSelect) sqlScan(ctx context.Context, root *AuthorizeCodesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(acs.fns))
	for _, fn := range acs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*acs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := acs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
