// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/authorizecodes"
	"authorization-service/ent/request"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AuthorizeCodes is the model entity for the AuthorizeCodes schema.
type AuthorizeCodes struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AuthorizeCodesQuery when eager-loading is set.
	Edges                  AuthorizeCodesEdges `json:"edges"`
	request_authorize_code *string
	selectValues           sql.SelectValues
}

// AuthorizeCodesEdges holds the relations/edges for other nodes in the graph.
type AuthorizeCodesEdges struct {
	// RequestID holds the value of the request_id edge.
	RequestID *Request `json:"request_id,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestIDOrErr returns the RequestID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AuthorizeCodesEdges) RequestIDOrErr() (*Request, error) {
	if e.loadedTypes[0] {
		if e.RequestID == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: request.Label}
		}
		return e.RequestID, nil
	}
	return nil, &NotLoadedError{edge: "request_id"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthorizeCodes) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authorizecodes.FieldActive:
			values[i] = new(sql.NullBool)
		case authorizecodes.FieldID:
			values[i] = new(sql.NullString)
		case authorizecodes.ForeignKeys[0]: // request_authorize_code
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthorizeCodes fields.
func (ac *AuthorizeCodes) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authorizecodes.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ac.ID = value.String
			}
		case authorizecodes.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				ac.Active = value.Bool
			}
		case authorizecodes.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_authorize_code", values[i])
			} else if value.Valid {
				ac.request_authorize_code = new(string)
				*ac.request_authorize_code = value.String
			}
		default:
			ac.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthorizeCodes.
// This includes values selected through modifiers, order, etc.
func (ac *AuthorizeCodes) Value(name string) (ent.Value, error) {
	return ac.selectValues.Get(name)
}

// QueryRequestID queries the "request_id" edge of the AuthorizeCodes entity.
func (ac *AuthorizeCodes) QueryRequestID() *RequestQuery {
	return NewAuthorizeCodesClient(ac.config).QueryRequestID(ac)
}

// Update returns a builder for updating this AuthorizeCodes.
// Note that you need to call AuthorizeCodes.Unwrap() before calling this method if this AuthorizeCodes
// was returned from a transaction, and the transaction was committed or rolled back.
func (ac *AuthorizeCodes) Update() *AuthorizeCodesUpdateOne {
	return NewAuthorizeCodesClient(ac.config).UpdateOne(ac)
}

// Unwrap unwraps the AuthorizeCodes entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ac *AuthorizeCodes) Unwrap() *AuthorizeCodes {
	_tx, ok := ac.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthorizeCodes is not a transactional entity")
	}
	ac.config.driver = _tx.drv
	return ac
}

// String implements the fmt.Stringer.
func (ac *AuthorizeCodes) String() string {
	var builder strings.Builder
	builder.WriteString("AuthorizeCodes(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ac.ID))
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", ac.Active))
	builder.WriteByte(')')
	return builder.String()
}

// AuthorizeCodesSlice is a parsable slice of AuthorizeCodes.
type AuthorizeCodesSlice []*AuthorizeCodes
