// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/authorizecodes"
	"authorization-service/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizeCodesDelete is the builder for deleting a AuthorizeCodes entity.
type AuthorizeCodesDelete struct {
	config
	hooks    []Hook
	mutation *AuthorizeCodesMutation
}

// Where appends a list predicates to the AuthorizeCodesDelete builder.
func (acd *AuthorizeCodesDelete) Where(ps ...predicate.AuthorizeCodes) *AuthorizeCodesDelete {
	acd.mutation.Where(ps...)
	return acd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (acd *AuthorizeCodesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, acd.sqlExec, acd.mutation, acd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (acd *AuthorizeCodesDelete) ExecX(ctx context.Context) int {
	n, err := acd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (acd *AuthorizeCodesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authorizecodes.Table, sqlgraph.NewFieldSpec(authorizecodes.FieldID, field.TypeString))
	if ps := acd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, acd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	acd.mutation.done = true
	return affected, err
}

// AuthorizeCodesDeleteOne is the builder for deleting a single AuthorizeCodes entity.
type AuthorizeCodesDeleteOne struct {
	acd *AuthorizeCodesDelete
}

// Where appends a list predicates to the AuthorizeCodesDelete builder.
func (acdo *AuthorizeCodesDeleteOne) Where(ps ...predicate.AuthorizeCodes) *AuthorizeCodesDeleteOne {
	acdo.acd.mutation.Where(ps...)
	return acdo
}

// Exec executes the deletion query.
func (acdo *AuthorizeCodesDeleteOne) Exec(ctx context.Context) error {
	n, err := acdo.acd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authorizecodes.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (acdo *AuthorizeCodesDeleteOne) ExecX(ctx context.Context) {
	if err := acdo.Exec(ctx); err != nil {
		panic(err)
	}
}
