// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/clients"
	"authorization-service/ent/idsessions"
	"authorization-service/ent/predicate"
	"authorization-service/ent/session"
	"context"
	"errors"
	"fmt"
	"net/url"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"golang.org/x/text/language"
)

// IDSessionsUpdate is the builder for updating IDSessions entities.
type IDSessionsUpdate struct {
	config
	hooks    []Hook
	mutation *IDSessionsMutation
}

// Where appends a list predicates to the IDSessionsUpdate builder.
func (isu *IDSessionsUpdate) Where(ps ...predicate.IDSessions) *IDSessionsUpdate {
	isu.mutation.Where(ps...)
	return isu
}

// SetRequestID sets the "request_id" field.
func (isu *IDSessionsUpdate) SetRequestID(s string) *IDSessionsUpdate {
	isu.mutation.SetRequestID(s)
	return isu
}

// SetRequestedAt sets the "requestedAt" field.
func (isu *IDSessionsUpdate) SetRequestedAt(t time.Time) *IDSessionsUpdate {
	isu.mutation.SetRequestedAt(t)
	return isu
}

// SetScopes sets the "scopes" field.
func (isu *IDSessionsUpdate) SetScopes(s []string) *IDSessionsUpdate {
	isu.mutation.SetScopes(s)
	return isu
}

// AppendScopes appends s to the "scopes" field.
func (isu *IDSessionsUpdate) AppendScopes(s []string) *IDSessionsUpdate {
	isu.mutation.AppendScopes(s)
	return isu
}

// SetGrantedScopes sets the "granted_scopes" field.
func (isu *IDSessionsUpdate) SetGrantedScopes(s []string) *IDSessionsUpdate {
	isu.mutation.SetGrantedScopes(s)
	return isu
}

// AppendGrantedScopes appends s to the "granted_scopes" field.
func (isu *IDSessionsUpdate) AppendGrantedScopes(s []string) *IDSessionsUpdate {
	isu.mutation.AppendGrantedScopes(s)
	return isu
}

// SetRequestedAudience sets the "requested_audience" field.
func (isu *IDSessionsUpdate) SetRequestedAudience(s []string) *IDSessionsUpdate {
	isu.mutation.SetRequestedAudience(s)
	return isu
}

// AppendRequestedAudience appends s to the "requested_audience" field.
func (isu *IDSessionsUpdate) AppendRequestedAudience(s []string) *IDSessionsUpdate {
	isu.mutation.AppendRequestedAudience(s)
	return isu
}

// SetGrantedAudience sets the "granted_audience" field.
func (isu *IDSessionsUpdate) SetGrantedAudience(s []string) *IDSessionsUpdate {
	isu.mutation.SetGrantedAudience(s)
	return isu
}

// AppendGrantedAudience appends s to the "granted_audience" field.
func (isu *IDSessionsUpdate) AppendGrantedAudience(s []string) *IDSessionsUpdate {
	isu.mutation.AppendGrantedAudience(s)
	return isu
}

// SetForm sets the "form" field.
func (isu *IDSessionsUpdate) SetForm(u url.Values) *IDSessionsUpdate {
	isu.mutation.SetForm(u)
	return isu
}

// SetLang sets the "lang" field.
func (isu *IDSessionsUpdate) SetLang(l language.Tag) *IDSessionsUpdate {
	isu.mutation.SetLang(l)
	return isu
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (isu *IDSessionsUpdate) SetNillableLang(l *language.Tag) *IDSessionsUpdate {
	if l != nil {
		isu.SetLang(*l)
	}
	return isu
}

// ClearLang clears the value of the "lang" field.
func (isu *IDSessionsUpdate) ClearLang() *IDSessionsUpdate {
	isu.mutation.ClearLang()
	return isu
}

// SetClientIDID sets the "client_id" edge to the Clients entity by ID.
func (isu *IDSessionsUpdate) SetClientIDID(id string) *IDSessionsUpdate {
	isu.mutation.SetClientIDID(id)
	return isu
}

// SetNillableClientIDID sets the "client_id" edge to the Clients entity by ID if the given value is not nil.
func (isu *IDSessionsUpdate) SetNillableClientIDID(id *string) *IDSessionsUpdate {
	if id != nil {
		isu = isu.SetClientIDID(*id)
	}
	return isu
}

// SetClientID sets the "client_id" edge to the Clients entity.
func (isu *IDSessionsUpdate) SetClientID(c *Clients) *IDSessionsUpdate {
	return isu.SetClientIDID(c.ID)
}

// SetSessionIDID sets the "session_id" edge to the Session entity by ID.
func (isu *IDSessionsUpdate) SetSessionIDID(id string) *IDSessionsUpdate {
	isu.mutation.SetSessionIDID(id)
	return isu
}

// SetNillableSessionIDID sets the "session_id" edge to the Session entity by ID if the given value is not nil.
func (isu *IDSessionsUpdate) SetNillableSessionIDID(id *string) *IDSessionsUpdate {
	if id != nil {
		isu = isu.SetSessionIDID(*id)
	}
	return isu
}

// SetSessionID sets the "session_id" edge to the Session entity.
func (isu *IDSessionsUpdate) SetSessionID(s *Session) *IDSessionsUpdate {
	return isu.SetSessionIDID(s.ID)
}

// Mutation returns the IDSessionsMutation object of the builder.
func (isu *IDSessionsUpdate) Mutation() *IDSessionsMutation {
	return isu.mutation
}

// ClearClientID clears the "client_id" edge to the Clients entity.
func (isu *IDSessionsUpdate) ClearClientID() *IDSessionsUpdate {
	isu.mutation.ClearClientID()
	return isu
}

// ClearSessionID clears the "session_id" edge to the Session entity.
func (isu *IDSessionsUpdate) ClearSessionID() *IDSessionsUpdate {
	isu.mutation.ClearSessionID()
	return isu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (isu *IDSessionsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, isu.sqlSave, isu.mutation, isu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (isu *IDSessionsUpdate) SaveX(ctx context.Context) int {
	affected, err := isu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (isu *IDSessionsUpdate) Exec(ctx context.Context) error {
	_, err := isu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (isu *IDSessionsUpdate) ExecX(ctx context.Context) {
	if err := isu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (isu *IDSessionsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(idsessions.Table, idsessions.Columns, sqlgraph.NewFieldSpec(idsessions.FieldID, field.TypeString))
	if ps := isu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := isu.mutation.RequestID(); ok {
		_spec.SetField(idsessions.FieldRequestID, field.TypeString, value)
	}
	if value, ok := isu.mutation.RequestedAt(); ok {
		_spec.SetField(idsessions.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := isu.mutation.Scopes(); ok {
		_spec.SetField(idsessions.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := isu.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldScopes, value)
		})
	}
	if value, ok := isu.mutation.GrantedScopes(); ok {
		_spec.SetField(idsessions.FieldGrantedScopes, field.TypeJSON, value)
	}
	if value, ok := isu.mutation.AppendedGrantedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldGrantedScopes, value)
		})
	}
	if value, ok := isu.mutation.RequestedAudience(); ok {
		_spec.SetField(idsessions.FieldRequestedAudience, field.TypeJSON, value)
	}
	if value, ok := isu.mutation.AppendedRequestedAudience(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldRequestedAudience, value)
		})
	}
	if value, ok := isu.mutation.GrantedAudience(); ok {
		_spec.SetField(idsessions.FieldGrantedAudience, field.TypeJSON, value)
	}
	if value, ok := isu.mutation.AppendedGrantedAudience(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldGrantedAudience, value)
		})
	}
	if value, ok := isu.mutation.Form(); ok {
		_spec.SetField(idsessions.FieldForm, field.TypeJSON, value)
	}
	if value, ok := isu.mutation.Lang(); ok {
		_spec.SetField(idsessions.FieldLang, field.TypeJSON, value)
	}
	if isu.mutation.LangCleared() {
		_spec.ClearField(idsessions.FieldLang, field.TypeJSON)
	}
	if isu.mutation.ClientIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.ClientIDTable,
			Columns: []string{idsessions.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := isu.mutation.ClientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.ClientIDTable,
			Columns: []string{idsessions.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if isu.mutation.SessionIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.SessionIDTable,
			Columns: []string{idsessions.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := isu.mutation.SessionIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.SessionIDTable,
			Columns: []string{idsessions.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, isu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idsessions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	isu.mutation.done = true
	return n, nil
}

// IDSessionsUpdateOne is the builder for updating a single IDSessions entity.
type IDSessionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IDSessionsMutation
}

// SetRequestID sets the "request_id" field.
func (isuo *IDSessionsUpdateOne) SetRequestID(s string) *IDSessionsUpdateOne {
	isuo.mutation.SetRequestID(s)
	return isuo
}

// SetRequestedAt sets the "requestedAt" field.
func (isuo *IDSessionsUpdateOne) SetRequestedAt(t time.Time) *IDSessionsUpdateOne {
	isuo.mutation.SetRequestedAt(t)
	return isuo
}

// SetScopes sets the "scopes" field.
func (isuo *IDSessionsUpdateOne) SetScopes(s []string) *IDSessionsUpdateOne {
	isuo.mutation.SetScopes(s)
	return isuo
}

// AppendScopes appends s to the "scopes" field.
func (isuo *IDSessionsUpdateOne) AppendScopes(s []string) *IDSessionsUpdateOne {
	isuo.mutation.AppendScopes(s)
	return isuo
}

// SetGrantedScopes sets the "granted_scopes" field.
func (isuo *IDSessionsUpdateOne) SetGrantedScopes(s []string) *IDSessionsUpdateOne {
	isuo.mutation.SetGrantedScopes(s)
	return isuo
}

// AppendGrantedScopes appends s to the "granted_scopes" field.
func (isuo *IDSessionsUpdateOne) AppendGrantedScopes(s []string) *IDSessionsUpdateOne {
	isuo.mutation.AppendGrantedScopes(s)
	return isuo
}

// SetRequestedAudience sets the "requested_audience" field.
func (isuo *IDSessionsUpdateOne) SetRequestedAudience(s []string) *IDSessionsUpdateOne {
	isuo.mutation.SetRequestedAudience(s)
	return isuo
}

// AppendRequestedAudience appends s to the "requested_audience" field.
func (isuo *IDSessionsUpdateOne) AppendRequestedAudience(s []string) *IDSessionsUpdateOne {
	isuo.mutation.AppendRequestedAudience(s)
	return isuo
}

// SetGrantedAudience sets the "granted_audience" field.
func (isuo *IDSessionsUpdateOne) SetGrantedAudience(s []string) *IDSessionsUpdateOne {
	isuo.mutation.SetGrantedAudience(s)
	return isuo
}

// AppendGrantedAudience appends s to the "granted_audience" field.
func (isuo *IDSessionsUpdateOne) AppendGrantedAudience(s []string) *IDSessionsUpdateOne {
	isuo.mutation.AppendGrantedAudience(s)
	return isuo
}

// SetForm sets the "form" field.
func (isuo *IDSessionsUpdateOne) SetForm(u url.Values) *IDSessionsUpdateOne {
	isuo.mutation.SetForm(u)
	return isuo
}

// SetLang sets the "lang" field.
func (isuo *IDSessionsUpdateOne) SetLang(l language.Tag) *IDSessionsUpdateOne {
	isuo.mutation.SetLang(l)
	return isuo
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (isuo *IDSessionsUpdateOne) SetNillableLang(l *language.Tag) *IDSessionsUpdateOne {
	if l != nil {
		isuo.SetLang(*l)
	}
	return isuo
}

// ClearLang clears the value of the "lang" field.
func (isuo *IDSessionsUpdateOne) ClearLang() *IDSessionsUpdateOne {
	isuo.mutation.ClearLang()
	return isuo
}

// SetClientIDID sets the "client_id" edge to the Clients entity by ID.
func (isuo *IDSessionsUpdateOne) SetClientIDID(id string) *IDSessionsUpdateOne {
	isuo.mutation.SetClientIDID(id)
	return isuo
}

// SetNillableClientIDID sets the "client_id" edge to the Clients entity by ID if the given value is not nil.
func (isuo *IDSessionsUpdateOne) SetNillableClientIDID(id *string) *IDSessionsUpdateOne {
	if id != nil {
		isuo = isuo.SetClientIDID(*id)
	}
	return isuo
}

// SetClientID sets the "client_id" edge to the Clients entity.
func (isuo *IDSessionsUpdateOne) SetClientID(c *Clients) *IDSessionsUpdateOne {
	return isuo.SetClientIDID(c.ID)
}

// SetSessionIDID sets the "session_id" edge to the Session entity by ID.
func (isuo *IDSessionsUpdateOne) SetSessionIDID(id string) *IDSessionsUpdateOne {
	isuo.mutation.SetSessionIDID(id)
	return isuo
}

// SetNillableSessionIDID sets the "session_id" edge to the Session entity by ID if the given value is not nil.
func (isuo *IDSessionsUpdateOne) SetNillableSessionIDID(id *string) *IDSessionsUpdateOne {
	if id != nil {
		isuo = isuo.SetSessionIDID(*id)
	}
	return isuo
}

// SetSessionID sets the "session_id" edge to the Session entity.
func (isuo *IDSessionsUpdateOne) SetSessionID(s *Session) *IDSessionsUpdateOne {
	return isuo.SetSessionIDID(s.ID)
}

// Mutation returns the IDSessionsMutation object of the builder.
func (isuo *IDSessionsUpdateOne) Mutation() *IDSessionsMutation {
	return isuo.mutation
}

// ClearClientID clears the "client_id" edge to the Clients entity.
func (isuo *IDSessionsUpdateOne) ClearClientID() *IDSessionsUpdateOne {
	isuo.mutation.ClearClientID()
	return isuo
}

// ClearSessionID clears the "session_id" edge to the Session entity.
func (isuo *IDSessionsUpdateOne) ClearSessionID() *IDSessionsUpdateOne {
	isuo.mutation.ClearSessionID()
	return isuo
}

// Where appends a list predicates to the IDSessionsUpdate builder.
func (isuo *IDSessionsUpdateOne) Where(ps ...predicate.IDSessions) *IDSessionsUpdateOne {
	isuo.mutation.Where(ps...)
	return isuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (isuo *IDSessionsUpdateOne) Select(field string, fields ...string) *IDSessionsUpdateOne {
	isuo.fields = append([]string{field}, fields...)
	return isuo
}

// Save executes the query and returns the updated IDSessions entity.
func (isuo *IDSessionsUpdateOne) Save(ctx context.Context) (*IDSessions, error) {
	return withHooks(ctx, isuo.sqlSave, isuo.mutation, isuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (isuo *IDSessionsUpdateOne) SaveX(ctx context.Context) *IDSessions {
	node, err := isuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (isuo *IDSessionsUpdateOne) Exec(ctx context.Context) error {
	_, err := isuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (isuo *IDSessionsUpdateOne) ExecX(ctx context.Context) {
	if err := isuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (isuo *IDSessionsUpdateOne) sqlSave(ctx context.Context) (_node *IDSessions, err error) {
	_spec := sqlgraph.NewUpdateSpec(idsessions.Table, idsessions.Columns, sqlgraph.NewFieldSpec(idsessions.FieldID, field.TypeString))
	id, ok := isuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IDSessions.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := isuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idsessions.FieldID)
		for _, f := range fields {
			if !idsessions.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idsessions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := isuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := isuo.mutation.RequestID(); ok {
		_spec.SetField(idsessions.FieldRequestID, field.TypeString, value)
	}
	if value, ok := isuo.mutation.RequestedAt(); ok {
		_spec.SetField(idsessions.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := isuo.mutation.Scopes(); ok {
		_spec.SetField(idsessions.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := isuo.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldScopes, value)
		})
	}
	if value, ok := isuo.mutation.GrantedScopes(); ok {
		_spec.SetField(idsessions.FieldGrantedScopes, field.TypeJSON, value)
	}
	if value, ok := isuo.mutation.AppendedGrantedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldGrantedScopes, value)
		})
	}
	if value, ok := isuo.mutation.RequestedAudience(); ok {
		_spec.SetField(idsessions.FieldRequestedAudience, field.TypeJSON, value)
	}
	if value, ok := isuo.mutation.AppendedRequestedAudience(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldRequestedAudience, value)
		})
	}
	if value, ok := isuo.mutation.GrantedAudience(); ok {
		_spec.SetField(idsessions.FieldGrantedAudience, field.TypeJSON, value)
	}
	if value, ok := isuo.mutation.AppendedGrantedAudience(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, idsessions.FieldGrantedAudience, value)
		})
	}
	if value, ok := isuo.mutation.Form(); ok {
		_spec.SetField(idsessions.FieldForm, field.TypeJSON, value)
	}
	if value, ok := isuo.mutation.Lang(); ok {
		_spec.SetField(idsessions.FieldLang, field.TypeJSON, value)
	}
	if isuo.mutation.LangCleared() {
		_spec.ClearField(idsessions.FieldLang, field.TypeJSON)
	}
	if isuo.mutation.ClientIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.ClientIDTable,
			Columns: []string{idsessions.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := isuo.mutation.ClientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.ClientIDTable,
			Columns: []string{idsessions.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if isuo.mutation.SessionIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.SessionIDTable,
			Columns: []string{idsessions.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := isuo.mutation.SessionIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idsessions.SessionIDTable,
			Columns: []string{idsessions.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IDSessions{config: isuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, isuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idsessions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	isuo.mutation.done = true
	return _node, nil
}
