// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/issuerpublickeys"
	"authorization-service/ent/predicate"
	"authorization-service/ent/subjectpublickeys"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IssuerPublicKeysQuery is the builder for querying IssuerPublicKeys entities.
type IssuerPublicKeysQuery struct {
	config
	ctx                  *QueryContext
	order                []issuerpublickeys.OrderOption
	inters               []Interceptor
	predicates           []predicate.IssuerPublicKeys
	withSubjectPublicKey *SubjectPublicKeysQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IssuerPublicKeysQuery builder.
func (ipkq *IssuerPublicKeysQuery) Where(ps ...predicate.IssuerPublicKeys) *IssuerPublicKeysQuery {
	ipkq.predicates = append(ipkq.predicates, ps...)
	return ipkq
}

// Limit the number of records to be returned by this query.
func (ipkq *IssuerPublicKeysQuery) Limit(limit int) *IssuerPublicKeysQuery {
	ipkq.ctx.Limit = &limit
	return ipkq
}

// Offset to start from.
func (ipkq *IssuerPublicKeysQuery) Offset(offset int) *IssuerPublicKeysQuery {
	ipkq.ctx.Offset = &offset
	return ipkq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ipkq *IssuerPublicKeysQuery) Unique(unique bool) *IssuerPublicKeysQuery {
	ipkq.ctx.Unique = &unique
	return ipkq
}

// Order specifies how the records should be ordered.
func (ipkq *IssuerPublicKeysQuery) Order(o ...issuerpublickeys.OrderOption) *IssuerPublicKeysQuery {
	ipkq.order = append(ipkq.order, o...)
	return ipkq
}

// QuerySubjectPublicKey chains the current query on the "subject_public_key" edge.
func (ipkq *IssuerPublicKeysQuery) QuerySubjectPublicKey() *SubjectPublicKeysQuery {
	query := (&SubjectPublicKeysClient{config: ipkq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ipkq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ipkq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issuerpublickeys.Table, issuerpublickeys.FieldID, selector),
			sqlgraph.To(subjectpublickeys.Table, subjectpublickeys.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, issuerpublickeys.SubjectPublicKeyTable, issuerpublickeys.SubjectPublicKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(ipkq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IssuerPublicKeys entity from the query.
// Returns a *NotFoundError when no IssuerPublicKeys was found.
func (ipkq *IssuerPublicKeysQuery) First(ctx context.Context) (*IssuerPublicKeys, error) {
	nodes, err := ipkq.Limit(1).All(setContextOp(ctx, ipkq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{issuerpublickeys.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) FirstX(ctx context.Context) *IssuerPublicKeys {
	node, err := ipkq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IssuerPublicKeys ID from the query.
// Returns a *NotFoundError when no IssuerPublicKeys ID was found.
func (ipkq *IssuerPublicKeysQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ipkq.Limit(1).IDs(setContextOp(ctx, ipkq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{issuerpublickeys.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) FirstIDX(ctx context.Context) string {
	id, err := ipkq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IssuerPublicKeys entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IssuerPublicKeys entity is found.
// Returns a *NotFoundError when no IssuerPublicKeys entities are found.
func (ipkq *IssuerPublicKeysQuery) Only(ctx context.Context) (*IssuerPublicKeys, error) {
	nodes, err := ipkq.Limit(2).All(setContextOp(ctx, ipkq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{issuerpublickeys.Label}
	default:
		return nil, &NotSingularError{issuerpublickeys.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) OnlyX(ctx context.Context) *IssuerPublicKeys {
	node, err := ipkq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IssuerPublicKeys ID in the query.
// Returns a *NotSingularError when more than one IssuerPublicKeys ID is found.
// Returns a *NotFoundError when no entities are found.
func (ipkq *IssuerPublicKeysQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ipkq.Limit(2).IDs(setContextOp(ctx, ipkq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{issuerpublickeys.Label}
	default:
		err = &NotSingularError{issuerpublickeys.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) OnlyIDX(ctx context.Context) string {
	id, err := ipkq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IssuerPublicKeysSlice.
func (ipkq *IssuerPublicKeysQuery) All(ctx context.Context) ([]*IssuerPublicKeys, error) {
	ctx = setContextOp(ctx, ipkq.ctx, "All")
	if err := ipkq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IssuerPublicKeys, *IssuerPublicKeysQuery]()
	return withInterceptors[[]*IssuerPublicKeys](ctx, ipkq, qr, ipkq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) AllX(ctx context.Context) []*IssuerPublicKeys {
	nodes, err := ipkq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IssuerPublicKeys IDs.
func (ipkq *IssuerPublicKeysQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ipkq.ctx.Unique == nil && ipkq.path != nil {
		ipkq.Unique(true)
	}
	ctx = setContextOp(ctx, ipkq.ctx, "IDs")
	if err = ipkq.Select(issuerpublickeys.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) IDsX(ctx context.Context) []string {
	ids, err := ipkq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ipkq *IssuerPublicKeysQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ipkq.ctx, "Count")
	if err := ipkq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ipkq, querierCount[*IssuerPublicKeysQuery](), ipkq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) CountX(ctx context.Context) int {
	count, err := ipkq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ipkq *IssuerPublicKeysQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ipkq.ctx, "Exist")
	switch _, err := ipkq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ipkq *IssuerPublicKeysQuery) ExistX(ctx context.Context) bool {
	exist, err := ipkq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IssuerPublicKeysQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ipkq *IssuerPublicKeysQuery) Clone() *IssuerPublicKeysQuery {
	if ipkq == nil {
		return nil
	}
	return &IssuerPublicKeysQuery{
		config:               ipkq.config,
		ctx:                  ipkq.ctx.Clone(),
		order:                append([]issuerpublickeys.OrderOption{}, ipkq.order...),
		inters:               append([]Interceptor{}, ipkq.inters...),
		predicates:           append([]predicate.IssuerPublicKeys{}, ipkq.predicates...),
		withSubjectPublicKey: ipkq.withSubjectPublicKey.Clone(),
		// clone intermediate query.
		sql:  ipkq.sql.Clone(),
		path: ipkq.path,
	}
}

// WithSubjectPublicKey tells the query-builder to eager-load the nodes that are connected to
// the "subject_public_key" edge. The optional arguments are used to configure the query builder of the edge.
func (ipkq *IssuerPublicKeysQuery) WithSubjectPublicKey(opts ...func(*SubjectPublicKeysQuery)) *IssuerPublicKeysQuery {
	query := (&SubjectPublicKeysClient{config: ipkq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ipkq.withSubjectPublicKey = query
	return ipkq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ipkq *IssuerPublicKeysQuery) GroupBy(field string, fields ...string) *IssuerPublicKeysGroupBy {
	ipkq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IssuerPublicKeysGroupBy{build: ipkq}
	grbuild.flds = &ipkq.ctx.Fields
	grbuild.label = issuerpublickeys.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ipkq *IssuerPublicKeysQuery) Select(fields ...string) *IssuerPublicKeysSelect {
	ipkq.ctx.Fields = append(ipkq.ctx.Fields, fields...)
	sbuild := &IssuerPublicKeysSelect{IssuerPublicKeysQuery: ipkq}
	sbuild.label = issuerpublickeys.Label
	sbuild.flds, sbuild.scan = &ipkq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IssuerPublicKeysSelect configured with the given aggregations.
func (ipkq *IssuerPublicKeysQuery) Aggregate(fns ...AggregateFunc) *IssuerPublicKeysSelect {
	return ipkq.Select().Aggregate(fns...)
}

func (ipkq *IssuerPublicKeysQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ipkq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ipkq); err != nil {
				return err
			}
		}
	}
	for _, f := range ipkq.ctx.Fields {
		if !issuerpublickeys.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ipkq.path != nil {
		prev, err := ipkq.path(ctx)
		if err != nil {
			return err
		}
		ipkq.sql = prev
	}
	return nil
}

func (ipkq *IssuerPublicKeysQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IssuerPublicKeys, error) {
	var (
		nodes       = []*IssuerPublicKeys{}
		_spec       = ipkq.querySpec()
		loadedTypes = [1]bool{
			ipkq.withSubjectPublicKey != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IssuerPublicKeys).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IssuerPublicKeys{config: ipkq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ipkq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ipkq.withSubjectPublicKey; query != nil {
		if err := ipkq.loadSubjectPublicKey(ctx, query, nodes, nil,
			func(n *IssuerPublicKeys, e *SubjectPublicKeys) { n.Edges.SubjectPublicKey = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ipkq *IssuerPublicKeysQuery) loadSubjectPublicKey(ctx context.Context, query *SubjectPublicKeysQuery, nodes []*IssuerPublicKeys, init func(*IssuerPublicKeys), assign func(*IssuerPublicKeys, *SubjectPublicKeys)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*IssuerPublicKeys)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.SubjectPublicKeys(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(issuerpublickeys.SubjectPublicKeyColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.issuer_public_keys_subject_public_key
		if fk == nil {
			return fmt.Errorf(`foreign-key "issuer_public_keys_subject_public_key" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "issuer_public_keys_subject_public_key" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ipkq *IssuerPublicKeysQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ipkq.querySpec()
	_spec.Node.Columns = ipkq.ctx.Fields
	if len(ipkq.ctx.Fields) > 0 {
		_spec.Unique = ipkq.ctx.Unique != nil && *ipkq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ipkq.driver, _spec)
}

func (ipkq *IssuerPublicKeysQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(issuerpublickeys.Table, issuerpublickeys.Columns, sqlgraph.NewFieldSpec(issuerpublickeys.FieldID, field.TypeString))
	_spec.From = ipkq.sql
	if unique := ipkq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ipkq.path != nil {
		_spec.Unique = true
	}
	if fields := ipkq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuerpublickeys.FieldID)
		for i := range fields {
			if fields[i] != issuerpublickeys.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ipkq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ipkq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ipkq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ipkq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ipkq *IssuerPublicKeysQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ipkq.driver.Dialect())
	t1 := builder.Table(issuerpublickeys.Table)
	columns := ipkq.ctx.Fields
	if len(columns) == 0 {
		columns = issuerpublickeys.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ipkq.sql != nil {
		selector = ipkq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ipkq.ctx.Unique != nil && *ipkq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ipkq.predicates {
		p(selector)
	}
	for _, p := range ipkq.order {
		p(selector)
	}
	if offset := ipkq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ipkq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IssuerPublicKeysGroupBy is the group-by builder for IssuerPublicKeys entities.
type IssuerPublicKeysGroupBy struct {
	selector
	build *IssuerPublicKeysQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ipkgb *IssuerPublicKeysGroupBy) Aggregate(fns ...AggregateFunc) *IssuerPublicKeysGroupBy {
	ipkgb.fns = append(ipkgb.fns, fns...)
	return ipkgb
}

// Scan applies the selector query and scans the result into the given value.
func (ipkgb *IssuerPublicKeysGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ipkgb.build.ctx, "GroupBy")
	if err := ipkgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssuerPublicKeysQuery, *IssuerPublicKeysGroupBy](ctx, ipkgb.build, ipkgb, ipkgb.build.inters, v)
}

func (ipkgb *IssuerPublicKeysGroupBy) sqlScan(ctx context.Context, root *IssuerPublicKeysQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ipkgb.fns))
	for _, fn := range ipkgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ipkgb.flds)+len(ipkgb.fns))
		for _, f := range *ipkgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ipkgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ipkgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IssuerPublicKeysSelect is the builder for selecting fields of IssuerPublicKeys entities.
type IssuerPublicKeysSelect struct {
	*IssuerPublicKeysQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ipks *IssuerPublicKeysSelect) Aggregate(fns ...AggregateFunc) *IssuerPublicKeysSelect {
	ipks.fns = append(ipks.fns, fns...)
	return ipks
}

// Scan applies the selector query and scans the result into the given value.
func (ipks *IssuerPublicKeysSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ipks.ctx, "Select")
	if err := ipks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssuerPublicKeysQuery, *IssuerPublicKeysSelect](ctx, ipks.IssuerPublicKeysQuery, ipks, ipks.inters, v)
}

func (ipks *IssuerPublicKeysSelect) sqlScan(ctx context.Context, root *IssuerPublicKeysQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ipks.fns))
	for _, fn := range ipks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ipks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ipks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
