// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/clients"
	"authorization-service/ent/pkces"
	"authorization-service/ent/session"
	"context"
	"errors"
	"fmt"
	"net/url"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"golang.org/x/text/language"
)

// PKCESCreate is the builder for creating a PKCES entity.
type PKCESCreate struct {
	config
	mutation *PKCESMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (pc *PKCESCreate) SetRequestID(s string) *PKCESCreate {
	pc.mutation.SetRequestID(s)
	return pc
}

// SetRequestedAt sets the "requestedAt" field.
func (pc *PKCESCreate) SetRequestedAt(t time.Time) *PKCESCreate {
	pc.mutation.SetRequestedAt(t)
	return pc
}

// SetScopes sets the "scopes" field.
func (pc *PKCESCreate) SetScopes(s []string) *PKCESCreate {
	pc.mutation.SetScopes(s)
	return pc
}

// SetGrantedScopes sets the "granted_scopes" field.
func (pc *PKCESCreate) SetGrantedScopes(s []string) *PKCESCreate {
	pc.mutation.SetGrantedScopes(s)
	return pc
}

// SetRequestedAudience sets the "requested_audience" field.
func (pc *PKCESCreate) SetRequestedAudience(s []string) *PKCESCreate {
	pc.mutation.SetRequestedAudience(s)
	return pc
}

// SetGrantedAudience sets the "granted_audience" field.
func (pc *PKCESCreate) SetGrantedAudience(s []string) *PKCESCreate {
	pc.mutation.SetGrantedAudience(s)
	return pc
}

// SetForm sets the "form" field.
func (pc *PKCESCreate) SetForm(u url.Values) *PKCESCreate {
	pc.mutation.SetForm(u)
	return pc
}

// SetLang sets the "lang" field.
func (pc *PKCESCreate) SetLang(l language.Tag) *PKCESCreate {
	pc.mutation.SetLang(l)
	return pc
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (pc *PKCESCreate) SetNillableLang(l *language.Tag) *PKCESCreate {
	if l != nil {
		pc.SetLang(*l)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *PKCESCreate) SetID(s string) *PKCESCreate {
	pc.mutation.SetID(s)
	return pc
}

// SetClientIDID sets the "client_id" edge to the Clients entity by ID.
func (pc *PKCESCreate) SetClientIDID(id string) *PKCESCreate {
	pc.mutation.SetClientIDID(id)
	return pc
}

// SetNillableClientIDID sets the "client_id" edge to the Clients entity by ID if the given value is not nil.
func (pc *PKCESCreate) SetNillableClientIDID(id *string) *PKCESCreate {
	if id != nil {
		pc = pc.SetClientIDID(*id)
	}
	return pc
}

// SetClientID sets the "client_id" edge to the Clients entity.
func (pc *PKCESCreate) SetClientID(c *Clients) *PKCESCreate {
	return pc.SetClientIDID(c.ID)
}

// SetSessionIDID sets the "session_id" edge to the Session entity by ID.
func (pc *PKCESCreate) SetSessionIDID(id string) *PKCESCreate {
	pc.mutation.SetSessionIDID(id)
	return pc
}

// SetNillableSessionIDID sets the "session_id" edge to the Session entity by ID if the given value is not nil.
func (pc *PKCESCreate) SetNillableSessionIDID(id *string) *PKCESCreate {
	if id != nil {
		pc = pc.SetSessionIDID(*id)
	}
	return pc
}

// SetSessionID sets the "session_id" edge to the Session entity.
func (pc *PKCESCreate) SetSessionID(s *Session) *PKCESCreate {
	return pc.SetSessionIDID(s.ID)
}

// Mutation returns the PKCESMutation object of the builder.
func (pc *PKCESCreate) Mutation() *PKCESMutation {
	return pc.mutation
}

// Save creates the PKCES in the database.
func (pc *PKCESCreate) Save(ctx context.Context) (*PKCES, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PKCESCreate) SaveX(ctx context.Context) *PKCES {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PKCESCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PKCESCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PKCESCreate) check() error {
	if _, ok := pc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "PKCES.request_id"`)}
	}
	if _, ok := pc.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requestedAt", err: errors.New(`ent: missing required field "PKCES.requestedAt"`)}
	}
	if _, ok := pc.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "PKCES.scopes"`)}
	}
	if _, ok := pc.mutation.GrantedScopes(); !ok {
		return &ValidationError{Name: "granted_scopes", err: errors.New(`ent: missing required field "PKCES.granted_scopes"`)}
	}
	if _, ok := pc.mutation.RequestedAudience(); !ok {
		return &ValidationError{Name: "requested_audience", err: errors.New(`ent: missing required field "PKCES.requested_audience"`)}
	}
	if _, ok := pc.mutation.GrantedAudience(); !ok {
		return &ValidationError{Name: "granted_audience", err: errors.New(`ent: missing required field "PKCES.granted_audience"`)}
	}
	if _, ok := pc.mutation.Form(); !ok {
		return &ValidationError{Name: "form", err: errors.New(`ent: missing required field "PKCES.form"`)}
	}
	return nil
}

func (pc *PKCESCreate) sqlSave(ctx context.Context) (*PKCES, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PKCES.ID type: %T", _spec.ID.Value)
		}
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PKCESCreate) createSpec() (*PKCES, *sqlgraph.CreateSpec) {
	var (
		_node = &PKCES{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(pkces.Table, sqlgraph.NewFieldSpec(pkces.FieldID, field.TypeString))
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.RequestID(); ok {
		_spec.SetField(pkces.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := pc.mutation.RequestedAt(); ok {
		_spec.SetField(pkces.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := pc.mutation.Scopes(); ok {
		_spec.SetField(pkces.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := pc.mutation.GrantedScopes(); ok {
		_spec.SetField(pkces.FieldGrantedScopes, field.TypeJSON, value)
		_node.GrantedScopes = value
	}
	if value, ok := pc.mutation.RequestedAudience(); ok {
		_spec.SetField(pkces.FieldRequestedAudience, field.TypeJSON, value)
		_node.RequestedAudience = value
	}
	if value, ok := pc.mutation.GrantedAudience(); ok {
		_spec.SetField(pkces.FieldGrantedAudience, field.TypeJSON, value)
		_node.GrantedAudience = value
	}
	if value, ok := pc.mutation.Form(); ok {
		_spec.SetField(pkces.FieldForm, field.TypeJSON, value)
		_node.Form = value
	}
	if value, ok := pc.mutation.Lang(); ok {
		_spec.SetField(pkces.FieldLang, field.TypeJSON, value)
		_node.Lang = value
	}
	if nodes := pc.mutation.ClientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pkces.ClientIDTable,
			Columns: []string{pkces.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.clients_pkce = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.SessionIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pkces.SessionIDTable,
			Columns: []string{pkces.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_pkce = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PKCESCreateBulk is the builder for creating many PKCES entities in bulk.
type PKCESCreateBulk struct {
	config
	builders []*PKCESCreate
}

// Save creates the PKCES entities in the database.
func (pcb *PKCESCreateBulk) Save(ctx context.Context) ([]*PKCES, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*PKCES, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PKCESMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PKCESCreateBulk) SaveX(ctx context.Context) []*PKCES {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PKCESCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PKCESCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
