// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/predicate"
	"authorization-service/ent/publickeyscopes"
	"authorization-service/ent/subjectpublickeys"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PublicKeyScopesQuery is the builder for querying PublicKeyScopes entities.
type PublicKeyScopesQuery struct {
	config
	ctx                    *QueryContext
	order                  []publickeyscopes.OrderOption
	inters                 []Interceptor
	predicates             []predicate.PublicKeyScopes
	withSubjectPublicKeyID *SubjectPublicKeysQuery
	withFKs                bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublicKeyScopesQuery builder.
func (pksq *PublicKeyScopesQuery) Where(ps ...predicate.PublicKeyScopes) *PublicKeyScopesQuery {
	pksq.predicates = append(pksq.predicates, ps...)
	return pksq
}

// Limit the number of records to be returned by this query.
func (pksq *PublicKeyScopesQuery) Limit(limit int) *PublicKeyScopesQuery {
	pksq.ctx.Limit = &limit
	return pksq
}

// Offset to start from.
func (pksq *PublicKeyScopesQuery) Offset(offset int) *PublicKeyScopesQuery {
	pksq.ctx.Offset = &offset
	return pksq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pksq *PublicKeyScopesQuery) Unique(unique bool) *PublicKeyScopesQuery {
	pksq.ctx.Unique = &unique
	return pksq
}

// Order specifies how the records should be ordered.
func (pksq *PublicKeyScopesQuery) Order(o ...publickeyscopes.OrderOption) *PublicKeyScopesQuery {
	pksq.order = append(pksq.order, o...)
	return pksq
}

// QuerySubjectPublicKeyID chains the current query on the "subject_public_key_id" edge.
func (pksq *PublicKeyScopesQuery) QuerySubjectPublicKeyID() *SubjectPublicKeysQuery {
	query := (&SubjectPublicKeysClient{config: pksq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pksq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pksq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(publickeyscopes.Table, publickeyscopes.FieldID, selector),
			sqlgraph.To(subjectpublickeys.Table, subjectpublickeys.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, publickeyscopes.SubjectPublicKeyIDTable, publickeyscopes.SubjectPublicKeyIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(pksq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PublicKeyScopes entity from the query.
// Returns a *NotFoundError when no PublicKeyScopes was found.
func (pksq *PublicKeyScopesQuery) First(ctx context.Context) (*PublicKeyScopes, error) {
	nodes, err := pksq.Limit(1).All(setContextOp(ctx, pksq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publickeyscopes.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) FirstX(ctx context.Context) *PublicKeyScopes {
	node, err := pksq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublicKeyScopes ID from the query.
// Returns a *NotFoundError when no PublicKeyScopes ID was found.
func (pksq *PublicKeyScopesQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pksq.Limit(1).IDs(setContextOp(ctx, pksq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publickeyscopes.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) FirstIDX(ctx context.Context) string {
	id, err := pksq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublicKeyScopes entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublicKeyScopes entity is found.
// Returns a *NotFoundError when no PublicKeyScopes entities are found.
func (pksq *PublicKeyScopesQuery) Only(ctx context.Context) (*PublicKeyScopes, error) {
	nodes, err := pksq.Limit(2).All(setContextOp(ctx, pksq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publickeyscopes.Label}
	default:
		return nil, &NotSingularError{publickeyscopes.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) OnlyX(ctx context.Context) *PublicKeyScopes {
	node, err := pksq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublicKeyScopes ID in the query.
// Returns a *NotSingularError when more than one PublicKeyScopes ID is found.
// Returns a *NotFoundError when no entities are found.
func (pksq *PublicKeyScopesQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pksq.Limit(2).IDs(setContextOp(ctx, pksq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publickeyscopes.Label}
	default:
		err = &NotSingularError{publickeyscopes.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) OnlyIDX(ctx context.Context) string {
	id, err := pksq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublicKeyScopesSlice.
func (pksq *PublicKeyScopesQuery) All(ctx context.Context) ([]*PublicKeyScopes, error) {
	ctx = setContextOp(ctx, pksq.ctx, "All")
	if err := pksq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublicKeyScopes, *PublicKeyScopesQuery]()
	return withInterceptors[[]*PublicKeyScopes](ctx, pksq, qr, pksq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) AllX(ctx context.Context) []*PublicKeyScopes {
	nodes, err := pksq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublicKeyScopes IDs.
func (pksq *PublicKeyScopesQuery) IDs(ctx context.Context) (ids []string, err error) {
	if pksq.ctx.Unique == nil && pksq.path != nil {
		pksq.Unique(true)
	}
	ctx = setContextOp(ctx, pksq.ctx, "IDs")
	if err = pksq.Select(publickeyscopes.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) IDsX(ctx context.Context) []string {
	ids, err := pksq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pksq *PublicKeyScopesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pksq.ctx, "Count")
	if err := pksq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pksq, querierCount[*PublicKeyScopesQuery](), pksq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) CountX(ctx context.Context) int {
	count, err := pksq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pksq *PublicKeyScopesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pksq.ctx, "Exist")
	switch _, err := pksq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pksq *PublicKeyScopesQuery) ExistX(ctx context.Context) bool {
	exist, err := pksq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublicKeyScopesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pksq *PublicKeyScopesQuery) Clone() *PublicKeyScopesQuery {
	if pksq == nil {
		return nil
	}
	return &PublicKeyScopesQuery{
		config:                 pksq.config,
		ctx:                    pksq.ctx.Clone(),
		order:                  append([]publickeyscopes.OrderOption{}, pksq.order...),
		inters:                 append([]Interceptor{}, pksq.inters...),
		predicates:             append([]predicate.PublicKeyScopes{}, pksq.predicates...),
		withSubjectPublicKeyID: pksq.withSubjectPublicKeyID.Clone(),
		// clone intermediate query.
		sql:  pksq.sql.Clone(),
		path: pksq.path,
	}
}

// WithSubjectPublicKeyID tells the query-builder to eager-load the nodes that are connected to
// the "subject_public_key_id" edge. The optional arguments are used to configure the query builder of the edge.
func (pksq *PublicKeyScopesQuery) WithSubjectPublicKeyID(opts ...func(*SubjectPublicKeysQuery)) *PublicKeyScopesQuery {
	query := (&SubjectPublicKeysClient{config: pksq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pksq.withSubjectPublicKeyID = query
	return pksq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		JSONWebKey jose.JSONWebKey `json:"json_web_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PublicKeyScopes.Query().
//		GroupBy(publickeyscopes.FieldJSONWebKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pksq *PublicKeyScopesQuery) GroupBy(field string, fields ...string) *PublicKeyScopesGroupBy {
	pksq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublicKeyScopesGroupBy{build: pksq}
	grbuild.flds = &pksq.ctx.Fields
	grbuild.label = publickeyscopes.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		JSONWebKey jose.JSONWebKey `json:"json_web_key,omitempty"`
//	}
//
//	client.PublicKeyScopes.Query().
//		Select(publickeyscopes.FieldJSONWebKey).
//		Scan(ctx, &v)
func (pksq *PublicKeyScopesQuery) Select(fields ...string) *PublicKeyScopesSelect {
	pksq.ctx.Fields = append(pksq.ctx.Fields, fields...)
	sbuild := &PublicKeyScopesSelect{PublicKeyScopesQuery: pksq}
	sbuild.label = publickeyscopes.Label
	sbuild.flds, sbuild.scan = &pksq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublicKeyScopesSelect configured with the given aggregations.
func (pksq *PublicKeyScopesQuery) Aggregate(fns ...AggregateFunc) *PublicKeyScopesSelect {
	return pksq.Select().Aggregate(fns...)
}

func (pksq *PublicKeyScopesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pksq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pksq); err != nil {
				return err
			}
		}
	}
	for _, f := range pksq.ctx.Fields {
		if !publickeyscopes.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pksq.path != nil {
		prev, err := pksq.path(ctx)
		if err != nil {
			return err
		}
		pksq.sql = prev
	}
	return nil
}

func (pksq *PublicKeyScopesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublicKeyScopes, error) {
	var (
		nodes       = []*PublicKeyScopes{}
		withFKs     = pksq.withFKs
		_spec       = pksq.querySpec()
		loadedTypes = [1]bool{
			pksq.withSubjectPublicKeyID != nil,
		}
	)
	if pksq.withSubjectPublicKeyID != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, publickeyscopes.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublicKeyScopes).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublicKeyScopes{config: pksq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pksq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pksq.withSubjectPublicKeyID; query != nil {
		if err := pksq.loadSubjectPublicKeyID(ctx, query, nodes, nil,
			func(n *PublicKeyScopes, e *SubjectPublicKeys) { n.Edges.SubjectPublicKeyID = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pksq *PublicKeyScopesQuery) loadSubjectPublicKeyID(ctx context.Context, query *SubjectPublicKeysQuery, nodes []*PublicKeyScopes, init func(*PublicKeyScopes), assign func(*PublicKeyScopes, *SubjectPublicKeys)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PublicKeyScopes)
	for i := range nodes {
		if nodes[i].subject_public_keys_public_key_scope == nil {
			continue
		}
		fk := *nodes[i].subject_public_keys_public_key_scope
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subjectpublickeys.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subject_public_keys_public_key_scope" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pksq *PublicKeyScopesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pksq.querySpec()
	_spec.Node.Columns = pksq.ctx.Fields
	if len(pksq.ctx.Fields) > 0 {
		_spec.Unique = pksq.ctx.Unique != nil && *pksq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pksq.driver, _spec)
}

func (pksq *PublicKeyScopesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publickeyscopes.Table, publickeyscopes.Columns, sqlgraph.NewFieldSpec(publickeyscopes.FieldID, field.TypeString))
	_spec.From = pksq.sql
	if unique := pksq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pksq.path != nil {
		_spec.Unique = true
	}
	if fields := pksq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publickeyscopes.FieldID)
		for i := range fields {
			if fields[i] != publickeyscopes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pksq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pksq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pksq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pksq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pksq *PublicKeyScopesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pksq.driver.Dialect())
	t1 := builder.Table(publickeyscopes.Table)
	columns := pksq.ctx.Fields
	if len(columns) == 0 {
		columns = publickeyscopes.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pksq.sql != nil {
		selector = pksq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pksq.ctx.Unique != nil && *pksq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pksq.predicates {
		p(selector)
	}
	for _, p := range pksq.order {
		p(selector)
	}
	if offset := pksq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pksq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublicKeyScopesGroupBy is the group-by builder for PublicKeyScopes entities.
type PublicKeyScopesGroupBy struct {
	selector
	build *PublicKeyScopesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pksgb *PublicKeyScopesGroupBy) Aggregate(fns ...AggregateFunc) *PublicKeyScopesGroupBy {
	pksgb.fns = append(pksgb.fns, fns...)
	return pksgb
}

// Scan applies the selector query and scans the result into the given value.
func (pksgb *PublicKeyScopesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pksgb.build.ctx, "GroupBy")
	if err := pksgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicKeyScopesQuery, *PublicKeyScopesGroupBy](ctx, pksgb.build, pksgb, pksgb.build.inters, v)
}

func (pksgb *PublicKeyScopesGroupBy) sqlScan(ctx context.Context, root *PublicKeyScopesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pksgb.fns))
	for _, fn := range pksgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pksgb.flds)+len(pksgb.fns))
		for _, f := range *pksgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pksgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pksgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublicKeyScopesSelect is the builder for selecting fields of PublicKeyScopes entities.
type PublicKeyScopesSelect struct {
	*PublicKeyScopesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pkss *PublicKeyScopesSelect) Aggregate(fns ...AggregateFunc) *PublicKeyScopesSelect {
	pkss.fns = append(pkss.fns, fns...)
	return pkss
}

// Scan applies the selector query and scans the result into the given value.
func (pkss *PublicKeyScopesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pkss.ctx, "Select")
	if err := pkss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicKeyScopesQuery, *PublicKeyScopesSelect](ctx, pkss.PublicKeyScopesQuery, pkss, pkss.inters, v)
}

func (pkss *PublicKeyScopesSelect) sqlScan(ctx context.Context, root *PublicKeyScopesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pkss.fns))
	for _, fn := range pkss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pkss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pkss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
