// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/clients"
	"authorization-service/ent/refreshtokens"
	"authorization-service/ent/session"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"golang.org/x/text/language"
)

// RefreshTokens is the model entity for the RefreshTokens schema.
type RefreshTokens struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// RequestedAt holds the value of the "requestedAt" field.
	RequestedAt time.Time `json:"requestedAt,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// GrantedScopes holds the value of the "granted_scopes" field.
	GrantedScopes []string `json:"granted_scopes,omitempty"`
	// RequestedAudience holds the value of the "requested_audience" field.
	RequestedAudience []string `json:"requested_audience,omitempty"`
	// GrantedAudience holds the value of the "granted_audience" field.
	GrantedAudience []string `json:"granted_audience,omitempty"`
	// Form holds the value of the "form" field.
	Form url.Values `json:"form,omitempty"`
	// Lang holds the value of the "lang" field.
	Lang language.Tag `json:"lang,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RefreshTokensQuery when eager-loading is set.
	Edges                 RefreshTokensEdges `json:"edges"`
	clients_refresh_token *string
	session_refresh_token *string
	selectValues          sql.SelectValues
}

// RefreshTokensEdges holds the relations/edges for other nodes in the graph.
type RefreshTokensEdges struct {
	// ClientID holds the value of the client_id edge.
	ClientID *Clients `json:"client_id,omitempty"`
	// SessionID holds the value of the session_id edge.
	SessionID *Session `json:"session_id,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ClientIDOrErr returns the ClientID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefreshTokensEdges) ClientIDOrErr() (*Clients, error) {
	if e.loadedTypes[0] {
		if e.ClientID == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: clients.Label}
		}
		return e.ClientID, nil
	}
	return nil, &NotLoadedError{edge: "client_id"}
}

// SessionIDOrErr returns the SessionID value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefreshTokensEdges) SessionIDOrErr() (*Session, error) {
	if e.loadedTypes[1] {
		if e.SessionID == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: session.Label}
		}
		return e.SessionID, nil
	}
	return nil, &NotLoadedError{edge: "session_id"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RefreshTokens) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case refreshtokens.FieldScopes, refreshtokens.FieldGrantedScopes, refreshtokens.FieldRequestedAudience, refreshtokens.FieldGrantedAudience, refreshtokens.FieldForm, refreshtokens.FieldLang:
			values[i] = new([]byte)
		case refreshtokens.FieldActive:
			values[i] = new(sql.NullBool)
		case refreshtokens.FieldID, refreshtokens.FieldRequestID:
			values[i] = new(sql.NullString)
		case refreshtokens.FieldRequestedAt:
			values[i] = new(sql.NullTime)
		case refreshtokens.ForeignKeys[0]: // clients_refresh_token
			values[i] = new(sql.NullString)
		case refreshtokens.ForeignKeys[1]: // session_refresh_token
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RefreshTokens fields.
func (rt *RefreshTokens) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case refreshtokens.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				rt.ID = value.String
			}
		case refreshtokens.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				rt.RequestID = value.String
			}
		case refreshtokens.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requestedAt", values[i])
			} else if value.Valid {
				rt.RequestedAt = value.Time
			}
		case refreshtokens.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rt.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case refreshtokens.FieldGrantedScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field granted_scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rt.GrantedScopes); err != nil {
					return fmt.Errorf("unmarshal field granted_scopes: %w", err)
				}
			}
		case refreshtokens.FieldRequestedAudience:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field requested_audience", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rt.RequestedAudience); err != nil {
					return fmt.Errorf("unmarshal field requested_audience: %w", err)
				}
			}
		case refreshtokens.FieldGrantedAudience:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field granted_audience", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rt.GrantedAudience); err != nil {
					return fmt.Errorf("unmarshal field granted_audience: %w", err)
				}
			}
		case refreshtokens.FieldForm:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field form", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rt.Form); err != nil {
					return fmt.Errorf("unmarshal field form: %w", err)
				}
			}
		case refreshtokens.FieldLang:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field lang", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rt.Lang); err != nil {
					return fmt.Errorf("unmarshal field lang: %w", err)
				}
			}
		case refreshtokens.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				rt.Active = value.Bool
			}
		case refreshtokens.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field clients_refresh_token", values[i])
			} else if value.Valid {
				rt.clients_refresh_token = new(string)
				*rt.clients_refresh_token = value.String
			}
		case refreshtokens.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_refresh_token", values[i])
			} else if value.Valid {
				rt.session_refresh_token = new(string)
				*rt.session_refresh_token = value.String
			}
		default:
			rt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RefreshTokens.
// This includes values selected through modifiers, order, etc.
func (rt *RefreshTokens) Value(name string) (ent.Value, error) {
	return rt.selectValues.Get(name)
}

// QueryClientID queries the "client_id" edge of the RefreshTokens entity.
func (rt *RefreshTokens) QueryClientID() *ClientsQuery {
	return NewRefreshTokensClient(rt.config).QueryClientID(rt)
}

// QuerySessionID queries the "session_id" edge of the RefreshTokens entity.
func (rt *RefreshTokens) QuerySessionID() *SessionQuery {
	return NewRefreshTokensClient(rt.config).QuerySessionID(rt)
}

// Update returns a builder for updating this RefreshTokens.
// Note that you need to call RefreshTokens.Unwrap() before calling this method if this RefreshTokens
// was returned from a transaction, and the transaction was committed or rolled back.
func (rt *RefreshTokens) Update() *RefreshTokensUpdateOne {
	return NewRefreshTokensClient(rt.config).UpdateOne(rt)
}

// Unwrap unwraps the RefreshTokens entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rt *RefreshTokens) Unwrap() *RefreshTokens {
	_tx, ok := rt.config.driver.(*txDriver)
	if !ok {
		panic("ent: RefreshTokens is not a transactional entity")
	}
	rt.config.driver = _tx.drv
	return rt
}

// String implements the fmt.Stringer.
func (rt *RefreshTokens) String() string {
	var builder strings.Builder
	builder.WriteString("RefreshTokens(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rt.ID))
	builder.WriteString("request_id=")
	builder.WriteString(rt.RequestID)
	builder.WriteString(", ")
	builder.WriteString("requestedAt=")
	builder.WriteString(rt.RequestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", rt.Scopes))
	builder.WriteString(", ")
	builder.WriteString("granted_scopes=")
	builder.WriteString(fmt.Sprintf("%v", rt.GrantedScopes))
	builder.WriteString(", ")
	builder.WriteString("requested_audience=")
	builder.WriteString(fmt.Sprintf("%v", rt.RequestedAudience))
	builder.WriteString(", ")
	builder.WriteString("granted_audience=")
	builder.WriteString(fmt.Sprintf("%v", rt.GrantedAudience))
	builder.WriteString(", ")
	builder.WriteString("form=")
	builder.WriteString(fmt.Sprintf("%v", rt.Form))
	builder.WriteString(", ")
	builder.WriteString("lang=")
	builder.WriteString(fmt.Sprintf("%v", rt.Lang))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", rt.Active))
	builder.WriteByte(')')
	return builder.String()
}

// RefreshTokensSlice is a parsable slice of RefreshTokens.
type RefreshTokensSlice []*RefreshTokens
