// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/clients"
	"authorization-service/ent/refreshtokens"
	"authorization-service/ent/session"
	"context"
	"errors"
	"fmt"
	"net/url"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"golang.org/x/text/language"
)

// RefreshTokensCreate is the builder for creating a RefreshTokens entity.
type RefreshTokensCreate struct {
	config
	mutation *RefreshTokensMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (rtc *RefreshTokensCreate) SetRequestID(s string) *RefreshTokensCreate {
	rtc.mutation.SetRequestID(s)
	return rtc
}

// SetRequestedAt sets the "requestedAt" field.
func (rtc *RefreshTokensCreate) SetRequestedAt(t time.Time) *RefreshTokensCreate {
	rtc.mutation.SetRequestedAt(t)
	return rtc
}

// SetScopes sets the "scopes" field.
func (rtc *RefreshTokensCreate) SetScopes(s []string) *RefreshTokensCreate {
	rtc.mutation.SetScopes(s)
	return rtc
}

// SetGrantedScopes sets the "granted_scopes" field.
func (rtc *RefreshTokensCreate) SetGrantedScopes(s []string) *RefreshTokensCreate {
	rtc.mutation.SetGrantedScopes(s)
	return rtc
}

// SetRequestedAudience sets the "requested_audience" field.
func (rtc *RefreshTokensCreate) SetRequestedAudience(s []string) *RefreshTokensCreate {
	rtc.mutation.SetRequestedAudience(s)
	return rtc
}

// SetGrantedAudience sets the "granted_audience" field.
func (rtc *RefreshTokensCreate) SetGrantedAudience(s []string) *RefreshTokensCreate {
	rtc.mutation.SetGrantedAudience(s)
	return rtc
}

// SetForm sets the "form" field.
func (rtc *RefreshTokensCreate) SetForm(u url.Values) *RefreshTokensCreate {
	rtc.mutation.SetForm(u)
	return rtc
}

// SetLang sets the "lang" field.
func (rtc *RefreshTokensCreate) SetLang(l language.Tag) *RefreshTokensCreate {
	rtc.mutation.SetLang(l)
	return rtc
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (rtc *RefreshTokensCreate) SetNillableLang(l *language.Tag) *RefreshTokensCreate {
	if l != nil {
		rtc.SetLang(*l)
	}
	return rtc
}

// SetActive sets the "active" field.
func (rtc *RefreshTokensCreate) SetActive(b bool) *RefreshTokensCreate {
	rtc.mutation.SetActive(b)
	return rtc
}

// SetID sets the "id" field.
func (rtc *RefreshTokensCreate) SetID(s string) *RefreshTokensCreate {
	rtc.mutation.SetID(s)
	return rtc
}

// SetClientIDID sets the "client_id" edge to the Clients entity by ID.
func (rtc *RefreshTokensCreate) SetClientIDID(id string) *RefreshTokensCreate {
	rtc.mutation.SetClientIDID(id)
	return rtc
}

// SetNillableClientIDID sets the "client_id" edge to the Clients entity by ID if the given value is not nil.
func (rtc *RefreshTokensCreate) SetNillableClientIDID(id *string) *RefreshTokensCreate {
	if id != nil {
		rtc = rtc.SetClientIDID(*id)
	}
	return rtc
}

// SetClientID sets the "client_id" edge to the Clients entity.
func (rtc *RefreshTokensCreate) SetClientID(c *Clients) *RefreshTokensCreate {
	return rtc.SetClientIDID(c.ID)
}

// SetSessionIDID sets the "session_id" edge to the Session entity by ID.
func (rtc *RefreshTokensCreate) SetSessionIDID(id string) *RefreshTokensCreate {
	rtc.mutation.SetSessionIDID(id)
	return rtc
}

// SetNillableSessionIDID sets the "session_id" edge to the Session entity by ID if the given value is not nil.
func (rtc *RefreshTokensCreate) SetNillableSessionIDID(id *string) *RefreshTokensCreate {
	if id != nil {
		rtc = rtc.SetSessionIDID(*id)
	}
	return rtc
}

// SetSessionID sets the "session_id" edge to the Session entity.
func (rtc *RefreshTokensCreate) SetSessionID(s *Session) *RefreshTokensCreate {
	return rtc.SetSessionIDID(s.ID)
}

// Mutation returns the RefreshTokensMutation object of the builder.
func (rtc *RefreshTokensCreate) Mutation() *RefreshTokensMutation {
	return rtc.mutation
}

// Save creates the RefreshTokens in the database.
func (rtc *RefreshTokensCreate) Save(ctx context.Context) (*RefreshTokens, error) {
	return withHooks(ctx, rtc.sqlSave, rtc.mutation, rtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rtc *RefreshTokensCreate) SaveX(ctx context.Context) *RefreshTokens {
	v, err := rtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rtc *RefreshTokensCreate) Exec(ctx context.Context) error {
	_, err := rtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtc *RefreshTokensCreate) ExecX(ctx context.Context) {
	if err := rtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtc *RefreshTokensCreate) check() error {
	if _, ok := rtc.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RefreshTokens.request_id"`)}
	}
	if _, ok := rtc.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requestedAt", err: errors.New(`ent: missing required field "RefreshTokens.requestedAt"`)}
	}
	if _, ok := rtc.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "RefreshTokens.scopes"`)}
	}
	if _, ok := rtc.mutation.GrantedScopes(); !ok {
		return &ValidationError{Name: "granted_scopes", err: errors.New(`ent: missing required field "RefreshTokens.granted_scopes"`)}
	}
	if _, ok := rtc.mutation.RequestedAudience(); !ok {
		return &ValidationError{Name: "requested_audience", err: errors.New(`ent: missing required field "RefreshTokens.requested_audience"`)}
	}
	if _, ok := rtc.mutation.GrantedAudience(); !ok {
		return &ValidationError{Name: "granted_audience", err: errors.New(`ent: missing required field "RefreshTokens.granted_audience"`)}
	}
	if _, ok := rtc.mutation.Form(); !ok {
		return &ValidationError{Name: "form", err: errors.New(`ent: missing required field "RefreshTokens.form"`)}
	}
	if _, ok := rtc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "RefreshTokens.active"`)}
	}
	return nil
}

func (rtc *RefreshTokensCreate) sqlSave(ctx context.Context) (*RefreshTokens, error) {
	if err := rtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RefreshTokens.ID type: %T", _spec.ID.Value)
		}
	}
	rtc.mutation.id = &_node.ID
	rtc.mutation.done = true
	return _node, nil
}

func (rtc *RefreshTokensCreate) createSpec() (*RefreshTokens, *sqlgraph.CreateSpec) {
	var (
		_node = &RefreshTokens{config: rtc.config}
		_spec = sqlgraph.NewCreateSpec(refreshtokens.Table, sqlgraph.NewFieldSpec(refreshtokens.FieldID, field.TypeString))
	)
	if id, ok := rtc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rtc.mutation.RequestID(); ok {
		_spec.SetField(refreshtokens.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := rtc.mutation.RequestedAt(); ok {
		_spec.SetField(refreshtokens.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := rtc.mutation.Scopes(); ok {
		_spec.SetField(refreshtokens.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := rtc.mutation.GrantedScopes(); ok {
		_spec.SetField(refreshtokens.FieldGrantedScopes, field.TypeJSON, value)
		_node.GrantedScopes = value
	}
	if value, ok := rtc.mutation.RequestedAudience(); ok {
		_spec.SetField(refreshtokens.FieldRequestedAudience, field.TypeJSON, value)
		_node.RequestedAudience = value
	}
	if value, ok := rtc.mutation.GrantedAudience(); ok {
		_spec.SetField(refreshtokens.FieldGrantedAudience, field.TypeJSON, value)
		_node.GrantedAudience = value
	}
	if value, ok := rtc.mutation.Form(); ok {
		_spec.SetField(refreshtokens.FieldForm, field.TypeJSON, value)
		_node.Form = value
	}
	if value, ok := rtc.mutation.Lang(); ok {
		_spec.SetField(refreshtokens.FieldLang, field.TypeJSON, value)
		_node.Lang = value
	}
	if value, ok := rtc.mutation.Active(); ok {
		_spec.SetField(refreshtokens.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if nodes := rtc.mutation.ClientIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtokens.ClientIDTable,
			Columns: []string{refreshtokens.ClientIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clients.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.clients_refresh_token = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rtc.mutation.SessionIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshtokens.SessionIDTable,
			Columns: []string{refreshtokens.SessionIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_refresh_token = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RefreshTokensCreateBulk is the builder for creating many RefreshTokens entities in bulk.
type RefreshTokensCreateBulk struct {
	config
	builders []*RefreshTokensCreate
}

// Save creates the RefreshTokens entities in the database.
func (rtcb *RefreshTokensCreateBulk) Save(ctx context.Context) ([]*RefreshTokens, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rtcb.builders))
	nodes := make([]*RefreshTokens, len(rtcb.builders))
	mutators := make([]Mutator, len(rtcb.builders))
	for i := range rtcb.builders {
		func(i int, root context.Context) {
			builder := rtcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefreshTokensMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rtcb *RefreshTokensCreateBulk) SaveX(ctx context.Context) []*RefreshTokens {
	v, err := rtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rtcb *RefreshTokensCreateBulk) Exec(ctx context.Context) error {
	_, err := rtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtcb *RefreshTokensCreateBulk) ExecX(ctx context.Context) {
	if err := rtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
