// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authorization-service/ent/predicate"
	"authorization-service/ent/request"
	"authorization-service/ent/session"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (su *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetExpiresAt sets the "expires_at" field.
func (su *SessionUpdate) SetExpiresAt(m map[string]time.Time) *SessionUpdate {
	su.mutation.SetExpiresAt(m)
	return su
}

// SetUsername sets the "username" field.
func (su *SessionUpdate) SetUsername(s string) *SessionUpdate {
	su.mutation.SetUsername(s)
	return su
}

// SetSubject sets the "subject" field.
func (su *SessionUpdate) SetSubject(s string) *SessionUpdate {
	su.mutation.SetSubject(s)
	return su
}

// SetExtra sets the "extra" field.
func (su *SessionUpdate) SetExtra(m map[string]interface{}) *SessionUpdate {
	su.mutation.SetExtra(m)
	return su
}

// ClearExtra clears the value of the "extra" field.
func (su *SessionUpdate) ClearExtra() *SessionUpdate {
	su.mutation.ClearExtra()
	return su
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (su *SessionUpdate) AddRequestIDs(ids ...string) *SessionUpdate {
	su.mutation.AddRequestIDs(ids...)
	return su
}

// AddRequests adds the "requests" edges to the Request entity.
func (su *SessionUpdate) AddRequests(r ...*Request) *SessionUpdate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddRequestIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (su *SessionUpdate) Mutation() *SessionMutation {
	return su.mutation
}

// ClearRequests clears all "requests" edges to the Request entity.
func (su *SessionUpdate) ClearRequests() *SessionUpdate {
	su.mutation.ClearRequests()
	return su
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (su *SessionUpdate) RemoveRequestIDs(ids ...string) *SessionUpdate {
	su.mutation.RemoveRequestIDs(ids...)
	return su
}

// RemoveRequests removes "requests" edges to Request entities.
func (su *SessionUpdate) RemoveRequests(r ...*Request) *SessionUpdate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SessionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SessionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeJSON, value)
	}
	if value, ok := su.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
	}
	if value, ok := su.mutation.Subject(); ok {
		_spec.SetField(session.FieldSubject, field.TypeString, value)
	}
	if value, ok := su.mutation.Extra(); ok {
		_spec.SetField(session.FieldExtra, field.TypeJSON, value)
	}
	if su.mutation.ExtraCleared() {
		_spec.ClearField(session.FieldExtra, field.TypeJSON)
	}
	if su.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RequestsTable,
			Columns: []string{session.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !su.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RequestsTable,
			Columns: []string{session.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RequestsTable,
			Columns: []string{session.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetExpiresAt sets the "expires_at" field.
func (suo *SessionUpdateOne) SetExpiresAt(m map[string]time.Time) *SessionUpdateOne {
	suo.mutation.SetExpiresAt(m)
	return suo
}

// SetUsername sets the "username" field.
func (suo *SessionUpdateOne) SetUsername(s string) *SessionUpdateOne {
	suo.mutation.SetUsername(s)
	return suo
}

// SetSubject sets the "subject" field.
func (suo *SessionUpdateOne) SetSubject(s string) *SessionUpdateOne {
	suo.mutation.SetSubject(s)
	return suo
}

// SetExtra sets the "extra" field.
func (suo *SessionUpdateOne) SetExtra(m map[string]interface{}) *SessionUpdateOne {
	suo.mutation.SetExtra(m)
	return suo
}

// ClearExtra clears the value of the "extra" field.
func (suo *SessionUpdateOne) ClearExtra() *SessionUpdateOne {
	suo.mutation.ClearExtra()
	return suo
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (suo *SessionUpdateOne) AddRequestIDs(ids ...string) *SessionUpdateOne {
	suo.mutation.AddRequestIDs(ids...)
	return suo
}

// AddRequests adds the "requests" edges to the Request entity.
func (suo *SessionUpdateOne) AddRequests(r ...*Request) *SessionUpdateOne {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddRequestIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (suo *SessionUpdateOne) Mutation() *SessionMutation {
	return suo.mutation
}

// ClearRequests clears all "requests" edges to the Request entity.
func (suo *SessionUpdateOne) ClearRequests() *SessionUpdateOne {
	suo.mutation.ClearRequests()
	return suo
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (suo *SessionUpdateOne) RemoveRequestIDs(ids ...string) *SessionUpdateOne {
	suo.mutation.RemoveRequestIDs(ids...)
	return suo
}

// RemoveRequests removes "requests" edges to Request entities.
func (suo *SessionUpdateOne) RemoveRequests(r ...*Request) *SessionUpdateOne {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveRequestIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (suo *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Session entity.
func (suo *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeJSON, value)
	}
	if value, ok := suo.mutation.Username(); ok {
		_spec.SetField(session.FieldUsername, field.TypeString, value)
	}
	if value, ok := suo.mutation.Subject(); ok {
		_spec.SetField(session.FieldSubject, field.TypeString, value)
	}
	if value, ok := suo.mutation.Extra(); ok {
		_spec.SetField(session.FieldExtra, field.TypeJSON, value)
	}
	if suo.mutation.ExtraCleared() {
		_spec.ClearField(session.FieldExtra, field.TypeJSON)
	}
	if suo.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RequestsTable,
			Columns: []string{session.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !suo.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RequestsTable,
			Columns: []string{session.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.RequestsTable,
			Columns: []string{session.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
