// Code generated by ent, DO NOT EDIT.

package publickeyscopes

import (
	"authorization-service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(sql.FieldContainsFold(FieldID, id))
}

// HasSubjectPublicKeyID applies the HasEdge predicate on the "subject_public_key_id" edge.
func HasSubjectPublicKeyID() predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SubjectPublicKeyIDTable, SubjectPublicKeyIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubjectPublicKeyIDWith applies the HasEdge predicate on the "subject_public_key_id" edge with a given conditions (other predicates).
func HasSubjectPublicKeyIDWith(preds ...predicate.SubjectPublicKeys) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(func(s *sql.Selector) {
		step := newSubjectPublicKeyIDStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PublicKeyScopes) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PublicKeyScopes) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PublicKeyScopes) predicate.PublicKeyScopes {
	return predicate.PublicKeyScopes(func(s *sql.Selector) {
		p(s.Not())
	})
}
